checks:
  commit-message:
    thresholds:
      fail: 0
  dependency-freshness:
    thresholds:
      warn: 5
      fail: 8
    level: minor
  code-similarity:
    thresholds:
      warn: 90
      fail: 110
