[workspace]
changelog_update = true
semver_check = false
git_release_enable = true
git_release_draft = true

[[package]]
name = "scute"
git_release_enable = true
changelog_include = ["scute-core", "scute-config", "scute-mcp"]

[[package]]
name = "scute-core"
git_release_enable = false

[[package]]
name = "scute-config"
git_release_enable = false

[[package]]
name = "scute-mcp"
git_release_enable = false

[[package]]
name = "scute-test-utils"
git_release_enable = false
