[workspace]
changelog_update = false
semver_check = false
git_release_enable = true
git_release_draft = true
git_tag_name = "v{{ version }}"

# Only create GitHub Releases for the CLI
[[package]]
name = "scute"
git_release_enable = true

[[package]]
name = "scute-core"
git_release_enable = false

[[package]]
name = "scute-config"
git_release_enable = false

[[package]]
name = "scute-mcp"
git_release_enable = false

[[package]]
name = "scute-test-utils"
git_release_enable = false
