name: Scute / CI

on:
  push:
    branches: [main]
    paths:
      - "crates/**"
      - "scripts/scute/**"
      - ".github/workflows/ci-scute.yml"
      - ".scute.yml"
  pull_request:
    paths:
      - "crates/**"
      - "scripts/scute/**"
      - ".github/workflows/ci-scute.yml"
      - ".scute.yml"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: rustup show
        working-directory: crates

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates

      - run: ./scripts/scute/ci.sh

  code-similarity:
    name: Code duplication
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        run: rustup show
        working-directory: crates

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: crates

      - name: Check for duplication
        run: |
          cd crates
          cargo run -q -- check code-similarity
