name: "Scute / Website CI"

on:
  push:
    branches: [main]
    paths: [website/**]
  pull_request:
    paths: [website/**]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - run: ./scripts/website/check.sh

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
      - name: Deploy
        run: ./scripts/website/deploy.sh ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
